version: "3"
services:

  app_proxy:
    environment:
      APP_HOST: qalasiaq-hello-world_1
      APP_PORT: 8000

  hello-world:
    image: crccheck/hello-world
    ports:
      - 8000:8000

    restart: always